### ISSUE TITLE
Bring it back on iOS 14-15

### ISSUE THREAD

**Issue by Isaac7u7** [DGh0st/No3DTouchWidgets#2]
Could be possible to create a tweak to do the opposite? I miss how this 3D touch view worked :(

thank you!

**Comment by DGh0st** [comment]
Yeah it would be possible. The difficulty would depend on whether default iOS still has the code for widgets in the 3D touch menu or not. If it doesn't then that would need to implemented from scratch.

In either case, that would be a new tweak (should request it on r/jailbreak or r/tweakbounty) that is unrelated to this one so closing this issue.
